window.CardShop = window.CardShop || {};

window.CardShop.config = {
  refreshMs: 5 * 60 * 1000,
  manualRefreshCost: 80,
  initialGold: 1200,
  assets: {
    shopBg: './assets/generated/shop-background.7289aaf8.webp',
    shelfFrame: './assets/generated/shelf-frame.f5d57463.webp',
    commonPack: './assets/generated/pack-common.6c28cdde.webp',
    premiumPack: './assets/generated/pack-premium.3641f824.webp',
    mysteryPack: './assets/generated/pack-mystery.79d21089.webp',
    cardBgCommon: './assets/generated/card-template-common.5f1831c4.webp',
    cardBgUncommon: './assets/generated/card-template-uncommon.2da19b43.webp',
    cardBgRare: './assets/generated/card-template-rare.efe6fcc6.webp',
    cardBgEpic: './assets/generated/card-template-epic.7fda81b7.webp',
    cardBgLegendary: './assets/generated/card-template-legendary.49989cb4.webp',
    cardBgShiny: './assets/generated/card-template-shiny.e2de9b15.webp',
    cover: './assets/generated/cover-monster-card-shop.d668afa3.webp',
    progressBar: './assets/generated/progress-gem-bar.260f2b42.webp',
  },
  packTypes: {
    common: { name: '普通卡包', cards: 3, image: 'commonPack', rareBoost: 0, shinyBonus: 0, market: 0.75, spawnWeight: 58 },
    type: { name: '属性卡包', cards: 3, image: 'commonPack', rareBoost: 0.08, shinyBonus: 0.004, market: 0.82, spawnWeight: 22 },
    premium: { name: '高级卡包', cards: 5, image: 'premiumPack', rareBoost: 0.16, shinyBonus: 0.008, market: 0.9, spawnWeight: 13 },
    shiny: { name: '闪光卡包', cards: 5, image: 'premiumPack', rareBoost: 0.22, shinyBonus: 0.035, market: 1.05, spawnWeight: 2 },
    mystery: { name: '神秘卡包', cards: 4, image: 'mysteryPack', rareBoost: 0.18, shinyBonus: 0.012, market: 1.15, spawnWeight: 5 },
  },
  rarities: [
    { key: 'legendary', name: '传说', minTotal: 580, value: 7.5, shinyChance: 0.006 },
    { key: 'epic', name: '史诗', minTotal: 530, value: 3.8, shinyChance: 0.012 },
    { key: 'rare', name: '稀有', minTotal: 450, value: 2.25, shinyChance: 0.02 },
    { key: 'uncommon', name: '优秀', minTotal: 330, value: 1.45, shinyChance: 0.03 },
    { key: 'common', name: '普通', minTotal: 0, value: 1, shinyChance: 0.04 },
  ],
  marketMoods: [
    { name: '冰点市场', rate: 0.55 },
    { name: '低迷', rate: 0.72 },
    { name: '平稳', rate: 1 },
    { name: '小幅升温', rate: 1.18 },
    { name: '火热', rate: 1.38 },
    { name: '收藏热潮', rate: 1.82 },
    { name: '拍卖狂欢', rate: 2.25 },
  ],
};
